var width = 2;
var height = 5;
var area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
var bill = 10;
var payment = 20;
var change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
var quizzes = 96;
var midterm = 93;
var final = 90;
var average = (quizzes + midterm + final) / 3;
console.log('value of average:', average);
console.log('typeof average:', typeof average);
var firstName = 'Daniel';
var lastName = 'Hahn';
var fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
var pH = 5;
var isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
var headCount = 300;
var isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
var motto = fullName;
motto = fullName + ' is the GOAT!';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
